src/java/com/lib/jsf/BookController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lib.jsf;

import com.lib.jpa.Book;
import com.lib.jpa.Bookcustomer;
import com.lib.jpaFacade.BookFacade;
import com.lib.namedBean.SessionUtils;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;


/**
 *
 * @author Евгений
 */
@Named
@SessionScoped
public class BookController implements Serializable {

    @EJB
    private com.lib.jpaFacade.BookFacade ejbFacade;
    @EJB
    private com.lib.jpaFacade.BookcustomerFacade bookCustomerFacade;
    private List<Book> items = null;
    private Book selected = new Book();
    private List<Book> customerBooks = null;
    private int genreFilter = 0;
    private int countryFilter = 0;
    private List<Book> filterBook;
    private int book;
    
    public int getBook(){
        return getItems().get(4).getAuthorId().getCountryId().getIdCountry();
    }

    public void resetFilters() {
        genreFilter = 0;
        countryFilter = 0;
    }

    public void filterCollection() {
        filterBook = new ArrayList<>(getItems());
        for (int i = 0; i < filterBook.size(); i++) {
            if (genreFilter != 0 && filterBook.get(i).getGenreId().getIdGenre() != genreFilter) {
                filterBook.remove(i);
                i--;
            }
            else if (countryFilter != 0 && filterBook.get(i).getAuthorId().getCountryId().getIdCountry() != countryFilter) {
                filterBook.remove(i);
                i--;
            }
        }
    }

    public List<Book> getFilterBook() {
        if (genreFilter == 0 && countryFilter == 0) {
            return getItems();
        }
        return filterBook;
    }

    public int getCountryFilter(){
        return this.countryFilter;
    }
    
    public void setCountryFilter(int country){
        this.countryFilter = country;
    }
    
    public void setGenreFilter(int genre) {
        this.genreFilter = genre;
    }

    public int getGenreFilter() {
        return genreFilter;
    }

    public List<Book> getCustomerItems() {
        customerBooks = new ArrayList<Book>();

        List<Bookcustomer> list = bookCustomerFacade.findAll();

        for (Bookcustomer bk : list) {
            if (bk.getBookcustomerPK().getCustomerId() == SessionUtils.getUserId()) {
                customerBooks.add(getBook(bk.getBookcustomerPK().getBookId()));
            }
        }
        return customerBooks;
    }

    /**
     * @return the selected
     */
    public Book getSelected() {
        return selected;
    }

    /**
     * @param selected the selected to set
     */
    public void setSelected(Book selected) {
        this.selected = selected;
    }

    private BookFacade getFacade() {
        return ejbFacade;
    }

    public List<Book> getItems() {
        items = getFacade().findAll();
        return items;
    }

    public void create() {
        if (selected != null) {
            getFacade().create(selected);
        }
        if (!isValidationFailed()) {
            items = null;
        }
    }

    public void update() {
        if (selected != null) {
            getFacade().edit(selected);
        }
    }

    public void destroy() {
        if (selected != null) {
            getFacade().remove(selected);
        }
        if (!isValidationFailed()) {
            selected = null;
            items = null;
        }
    }

    public Book getBook(Integer id) {
        return getFacade().find(id);
    }

    private static boolean isValidationFailed() {
        return FacesContext.getCurrentInstance().isValidationFailed();
    }
}

src/java/com/lib/namedBean/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lib.namedBean;

import java.io.Serializable;
import java.util.List;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.http.HttpSession;
import com.lib.jpa.Customer;
import javax.inject.Inject;

/**
 *
 * @author Евгений
 */
@Named
@SessionScoped
public class LoginBean implements Serializable {

    private Customer currentUser;
    private String login;
    private String password;
    private boolean isLogin;
    @Inject
    private com.lib.jsf.CustomerController customerContoller;

    public String login() {
        boolean flag = false;
        List<Customer> list = customerContoller.getItems();

        for (com.lib.jpa.Customer item : list) {
            if (item.getPassword().equals(getPassword()) && item.getEmail().equals(getLogin())) {
                currentUser = item;
                isLogin = true;
                flag = true;
            }
        }

        if (flag) {
            HttpSession session = SessionUtils.getSession();
            session.setAttribute("username", currentUser.getRealname());
            session.setAttribute("email", currentUser.getEmail());
            session.setAttribute("userId", currentUser.getIdCustomer());
            return "welcomePrimefaces";
        } else {
            FacesContext.getCurrentInstance().addMessage("errorLoginMessage",
                    new FacesMessage("Неправильный логин или пароль"));
            return "login";
        }
    }

    public String logout() {
        HttpSession session = SessionUtils.getSession();
        session.invalidate();
        isLogin = false;
        return "index";
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getLogin() {
        return this.login;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * @return the isLogin
     */
    public boolean isIsLogin() {
        return isLogin;
    }

    /**
     * @return the currentUser
     */
    public Customer getCurrentUser() {
        return currentUser;
    }

    /**
     * @param currentUser the currentUser to set
     */
    public void setCurrentUser(Customer currentUser) {
        this.currentUser = currentUser;
    }

}

web/customerPage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="stylesheet.css"/>
    </h:head>
    <h:body>
        <p:layout fullPage="true">
            <p:layoutUnit size="125" position="north">
                <p:outputLabel value="email: #{loginBean.currentUser.email}"/><br/>
                <p:outputLabel value="Имя: #{loginBean.currentUser.realname}"/><br/>
                <p:outputLabel value="Дата регистрации: #{loginBean.currentUser.registrationdate}"/><br/>
                <p:link value="Назад" href="welcomePrimefaces.xhtml"/>
            </p:layoutUnit>
            <p:layoutUnit size="500" position="center">
                <h3>Коллекция:</h3>
                <p:dataGrid var="book" value="#{bookController.customerItems}" columns="3" rows="12" >
                    <p:panel header="#{book.name}">
                        <h:panelGrid columns="1" style="width: 50px">                
                            <p:graphicImage library="bookcover" name="#{book.name}.jpg" height="300" width="200" />
                            <h:outputText value="Автор: #{book.authorId.fio}"/>
                            <h:outputText value="Страна: #{book.authorId.countryId.name}"/>
                            <p:button value="Читать" outcome="resources/booktext/#{book.name}.pdf"/>
                            <h:form>
                                <p:commandButton ajax ="false" value="Удалить" action="#{customerController.deleteBook(book)}"/>
                            </h:form>
                        </h:panelGrid>
                    </p:panel>
                </p:dataGrid>
            </p:layoutUnit>
        </p:layout>
    </h:body>
</html>

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        Hello from Facelets
        <br />
        <h:link outcome="welcomePrimefaces" value="Страница приветствия Primefaces" />
    </h:body>
</html>

web/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <h:form>
            <p:panelGrid columns="2">
                <p:outputLabel value="Email"/>
                <p:inputText value="#{loginBean.login}"/>
                <p:outputLabel value="Password"/>
                <p:password value="#{loginBean.password}"/>
            </p:panelGrid>
            <p:commandButton value="Войти" action="#{loginBean.login()}" ajax="false"/>
            <h:messages id="errorLoginMessage" />

        </h:form>
    </h:body>
</html>

web/registration.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="stylesheet.css"/>
    </h:head>
    <h:body>
        <div>
            <h:form>
                <p:panelGrid columns="3">
                    
                    <p:outputLabel value="email"/>
                    <p:inputText id="emailInput" required="true"
                                 value="#{customerController.selected.email}"
                                 validator="emailValidator"/>
                    <p:message for="emailInput"/>
                    
                    <p:outputLabel value="Пароль"/>
                    <p:password id="passwordInput" required="true"
                                value ="#{customerController.selected.password}"/>
                    <p:message for="passwordInput"/>
                    
                    <p:outputLabel id="nameInput" value="Настоящее имя"/>                  
                    <p:inputText required="true" value ="#{customerController.selected.realname}"/>
                    <p:message for="nameInput"/>
                    
                </p:panelGrid>
                <br></br>
                <p:commandButton ajax = "false" value="Регистрация" action="#{customerController.create()}"/>
            </h:form>
        </div>
    </h:body>
</html>

web/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true" closable="true" collapsible="true">
                    <p:link rendered="#{!loginBean.isLogin}" value="Войти" href="login.xhtml"/>
                    <p:link rendered="#{!loginBean.isLogin}" value="Регистрация" href="registration.xhtml"/>
                    <p:outputLabel rendered="#{loginBean.isLogin}" value="Здравствуйте, #{loginBean.currentUser.realname}"/>
                    <p:link rendered="#{loginBean.isLogin}" value="Кабинет" href="customerPage.xhtml"/>
                    <h:form>
                        <p:commandLink rendered="#{loginBean.isLogin}" value="Выйти" action="#{loginBean.logout()}" ajax="false"/>
                    </h:form>
                </p:layoutUnit>


                <p:layoutUnit position="south" size="75" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <p:layoutUnit position="west" size="200" header="Left" collapsible="true">
                    <h:form>
                        <h:outputText value="Жанр:"/>
                        <p:selectOneMenu value="#{bookController.genreFilter}">
                            <f:selectItem itemLabel="Выберете жанр" itemValue="0"/>
                            <f:selectItems value="#{genreController.items}" var="genres" 
                                           itemLabel="#{genres.name}" itemValue="#{genres.idGenre}"/>
                        </p:selectOneMenu>
                        
                        <h:outputText value="Страна:"/>
                        <p:selectOneMenu value="#{bookController.countryFilter}">
                            <f:selectItem itemLabel="Выберете страну" itemValue="0"/>
                            <f:selectItems value="#{countryController.items}" var="country" 
                                           itemLabel="#{country.name}" itemValue="#{country.idCountry}"/>
                        </p:selectOneMenu> 
                        <p:commandButton value="Применить" ajax="false" action="#{bookController.filterCollection()}"/>
                    </h:form>
                    <p:outputLabel value ="#{bookController.book}"/>
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    <p:dataGrid var="book" value="#{bookController.filterBook}" columns="3" rows="12" >
                        <p:panel header="#{book.name}">
                            <h:panelGrid columns="1">                
                                <p:graphicImage library="bookcover" name="#{book.name}.jpg" height="300" width="200" />
                                <h:outputText value="Автор: #{book.authorId.fio}"/>
                                <h:outputText value="Страна: #{book.authorId.countryId.name}"/>
                                <p:button value="Читать" outcome="resources/booktext/#{book.name}.pdf"/>
                                <h:form>
                                    <p:commandButton ajax ="false" rendered="#{loginBean.isLogin and !customerController.isAddedBook(book)}" value="Добавить" action="#{customerController.addBook(book)}"/>
                                </h:form>
                            </h:panelGrid>
                        </p:panel>
                    </p:dataGrid>
                </p:layoutUnit>


            </p:layout>

        </h:body>

    </f:view>
</html>